apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    # k8s-app: prometheus
    operated-prometheus: "true"
  name: prometheus
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: web
  selector:
    matchLabels:
      operated-prometheus: "true"
